"""Akta news-type taxonomy — a static snapshot of the published `news-tags.csv`.

Kept in the CLI so the package is fully independent of the MCP. The MCP has its
own copy (`akta_mcp/tools/news_tags.py`); keep both in sync if the CSV changes:
https://delightful-beach-02437b20f.7.azurestaticapps.net/news-tags.csv
"""

# Leaf-tag category prefixes → human category names.
NEWS_CATEGORIES = {
    "OT": "Others",
    "SD": "Strategic Developments",
    "CM": "Capital Markets & Transactions",
    "LG": "Leadership & Governance",
    "WT": "Workforce & Talent",
    "FR": "Financial Results & Performance",
    "RC": "Regulatory & Compliance",
    "MM": "Macro & Market Environment",
    "MD": "Market Dynamics",
    "II": "Industry Disruption & Innovation",
    "RK": "Risk & Crisis Events",
}

# (code, name) leaf tags. `news signals --type-code …` sends these as `type_list`.
NEWS_TAGS = [
    ("OT01", "Others"),
    ("SD01", "Product Launches & Enhancements"),
    ("SD02", "Partnerships & Alliances"),
    ("SD03", "Geographic Expansion"),
    ("SD04", "Operational Milestones"),
    ("SD05", "Market Share & Positioning"),
    ("SD06", "Digital Transformation"),
    ("SD07", "Brand & Marketing Initiatives"),
    ("SD08", "Research, Development & Innovation"),
    ("SD09", "Sustainability & ESG"),
    ("SD10", "Pricing & Commercial Strategy"),
    ("SD11", "Awards, Rankings & Recognitions"),
    ("CM01", "Equity Fund-Raising"),
    ("CM02", "Debt Financing"),
    ("CM03", "Mergers & Acquisitions"),
    ("CM04", "Divestitures & Asset Sales"),
    ("CM05", "IPOs & Follow-on Offerings"),
    ("CM06", "SPAC Deals & De-SPACs"),
    ("CM07", "Secondary Transactions"),
    ("CM08", "Shareholder Returns (Buybacks & Dividends)"),
    ("CM09", "Valuation Events"),
    ("CM10", "Deal Flow & Volume Statistics"),
    ("CM11", "Public-to-Private/Take-Private"),
    ("CM12", "Daily Stock Market News"),
    ("LG01", "C-Suite Appointments & Departures"),
    ("LG02", "Board Composition & Changes"),
    ("LG03", "Succession Planning"),
    ("LG04", "Organisational Restructuring"),
    ("LG05", "Executive Commentary & Interviews"),
    ("LG06", "Conflicts of Interest & Related-Party Transactions"),
    ("WT01", "Strategic Hiring"),
    ("WT02", "Workforce Reductions"),
    ("WT03", "Compensation & Benefits"),
    ("WT04", "Culture & Workplace Practices"),
    ("WT05", "Talent-Market Dynamics"),
    ("FR01", "Earnings Releases"),
    ("FR02", "Revenue & Growth Metrics"),
    ("FR03", "Profitability & Margins"),
    ("FR04", "Cash Flow & Capital Expenditure"),
    ("FR05", "Guidance & Forecast Revisions"),
    ("FR06", "Credit-Rating Actions"),
    ("FR07", "Sector Performance Dashboards"),
    ("RC01", "Regulatory Approvals & Certifications"),
    ("RC02", "Policy & Legislative Changes"),
    ("RC03", "Legal Proceedings & Litigation"),
    ("RC04", "Compliance & Reporting Updates"),
    ("RC05", "Intellectual Property"),
    ("RC06", "Antitrust & Competition"),
    ("RC07", "Data Privacy & Cybersecurity Regulation"),
    ("RC08", "Tax & Accounting Rules"),
    ("MM01", "Economic Indicators"),
    ("MM02", "Monetary Policy"),
    ("MM03", "Fiscal Policy"),
    ("MM04", "Trade, Tariffs & Sanctions"),
    ("MM05", "Consumer Behaviour & Spending"),
    ("MM06", "Labor-Market Statistics"),
    ("MM07", "Sector Outlook & Forecasts"),
    ("MD01", "Market Indices Performance"),
    ("MD02", "Institutional Flows & Positioning"),
    ("MD03", "Sector Rotation"),
    ("MD04", "Volatility & Risk Appetite"),
    ("MD05", "FX & Commodity Pricing"),
    ("MD06", "Liquidity Conditions"),
    ("MD07", "Investor Sentiment"),
    ("II01", "Emerging Technologies"),
    ("II02", "Technology Adoption & Disruption"),
    ("II03", "Business-Model Evolution"),
    ("II04", "Competitive Threats"),
    ("II05", "Market-Structure Changes"),
    ("RK01", "Geopolitical Risk"),
    ("RK02", "Public-Health Crises"),
    ("RK03", "Natural Disasters"),
    ("RK04", "Operational Disruptions"),
    ("RK05", "Cybersecurity Incidents"),
    ("RK06", "Reputational Damage"),
    ("RK07", "Financial Distress & Restructuring"),
    ("RK08", "Supply-Chain Disruptions"),
]
